### ISSUE TITLE
runner_sim.py and runner_competition_evaluator.py work differently

### ISSUE THREAD

**Issue by josephinekoe** [augcog/ROAR#28]
**Describe the bug**
The car does not behave the same way when running runner_sim.py vs. runner_competition_evaluator.py.

**To Reproduce**
1. Run both scripts and observe the speed of the car.

**Expected behavior**
The car speeds up more during runner_sim.py.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - GPU

**Additional context**

**Comment by RyanC1681** [comment]
Hi, 
Have you resolved this issue? I got error on runner_competition_evaluator.py that got error as below, but runner_sim.py works in ubuntu 20.04 and both work in Win10.
Any idea and which file to modify to improve the drive speed for runner_sim.py and runner_competition_evaluator.py? 
Why Win10 got higher FPS(~30fps) than ubuntu(~15fps)?
Thanks,
Traceback (most recent call last):
  File "/home/Downloads/ROAR-main/runner_competition_evaluator.py", line 99, in <module> main()
  File "/home/Downloads/ROAR-main/runner_competition_evaluator.py", line 92, in main num_laps=num_laps
  File "/home/Downloads/ROAR-main/runner_competition_evaluator.py", line 58, in run lap_count=num_laps)
TypeError: __init__() got an unexpected keyword argument 'lap_count'

**Comment by wuxiaohua1011** [comment]
Following through the Traceback, i believe `lap_count` should be there?
https://github.com/augcog/ROAR_Sim/blob/b579af0227b1090678eb1e43c398b72634d2090f/carla_client/carla_runner.py#L34

For differnet FPS, perhaps your ubuntu isn't using GPU? 

Please use `nvidia-smi` command to check if you are using GPU

**Comment by RyanC1681** [comment]
Hi,  thanks for the info. I was able to run in win10 and ubuntu and nvidia-smi did show lower FPS or GPU utilization than win10.
I am wondering how to get into competition mode with other cars running to test car avoidance.
Thanks,
